version: "3.8"
volumes:
  postgres_volume:

services:
  pg-go-db:
    image: postgres:14-alpine3.15
    container_name: "pg-go"
    environment:
      - POSTGRES_DB=note-service
      - POSTGRES_USER=note-service-user
      - POSTGRES_PASSWORD=note-service-password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 54321:5432
